# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Orange_Blog
subtitle: "look at you!"
description: "welcome to my blog!!!"
keywords:
author: Orange
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project' #这里是你的域名，如果你是用github的话，就是你的github的用户名.github.io/你的项目名字
url: http://example.com
permalink: :year/:month/:day/:title/ #这里是你的文章的链接格式，我这里是年/月/日/标题
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks #设置为false可以去掉链接中的index.html
  trailing_html: true # Set to false to remove trailing '.html' from permalinks #设置为false可以去掉链接中的.html

# Directory
source_dir: source #这里是你存放文章的文件夹
public_dir: public #这里是你生成的网页放的文件夹
tag_dir: tags #标签的文件夹
archive_dir: archives #归档的文件夹
category_dir: categories #分类的文件夹
code_dir: downloads/code #代码的文件夹
i18n_dir: :lang # Internationalization（国际化）的文件夹
skip_render:

# Writing
new_post_name: :title.md # File name of new posts #新文章的文件名
default_layout: post
titlecase: false # Transform title into titlecase #标题是否大写
external_link:
  enable: true # Open external links in new tab #是否在新标签页打开链接
  field: site # Apply to the whole site #应用到整个网站
  exclude: "" #不需要新标签页打开的链接
filename_case: 0
render_drafts: false #是否渲染草稿
post_asset_folder: false #是否建立文章的文件夹
relative_link: false #是否使用相对链接
future: true #是否允许发布未来的文章
highlight: #代码高亮
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: "git"
  repo: git@github.com:OrangeZSW/OrangeZSW.github.io.git
  branch: main
