name: Docker Image CI

on:
  push:
    branches:
      - master_blog
      - master_blog_ui
  workflow_dispatch:

env:
  # 后端源代码目录
  BACKEND_DIR: ./blog/service
  # 前端源代码目录
  FRONTEND_DIR: ./blog/ui
  # Dockerfile 项目路径
  DOCKERFILE_DIR: ./blog
  # 服务器目标目录
  DEPLOY_TARGET: /home/nginx-ui/www/dist
  # 镜像名称
  IMAGE_PATH: /zorange/blog
  # 阿里云镜像仓库
  DOCKER_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}

jobs:
  build-frontend:
    if: github.ref == 'refs/heads/master_blog_ui'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master_blog_ui


      - name: 安装pnpm环境
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        working-directory: ${{ env.FRONTEND_DIR }}
        run: pnpm install

      - name: Build frontend
        working-directory: ${{ env.FRONTEND_DIR }}
        run: pnpm run build

      - name: Remove old files
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: rm -rf ${{ env.DEPLOY_TARGET }}/*

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "${{ env.FRONTEND_DIR }}/dist/*"
          target: ${{ env.DEPLOY_TARGET }}
          overwrite: true